# Generated by Django 2.2.1 on 2019-10-05 22:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=250)),
                ('date', models.DateField(default=datetime.datetime(2019, 10, 5, 22, 5, 11, 576961, tzinfo=utc))),
                ('location', models.CharField(max_length=50)),
                ('photos', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(max_length=50)),
                ('photo_desc', models.CharField(max_length=250)),
                ('photo_date', models.DateField(default=datetime.datetime(2019, 10, 5, 22, 5, 11, 576961, tzinfo=utc))),
                ('photo_location', models.CharField(max_length=50)),
                ('file_type', models.CharField(max_length=10)),
                ('is_favorite', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictureQ.Album')),
            ],
        ),
    ]
