# Generated by Django 2.2.1 on 2019-10-05 22:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pictureQ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 5, 22, 17, 54, 830617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='album',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 5, 22, 17, 54, 831617, tzinfo=utc)),
        ),
    ]
