# Generated by Django 2.2.1 on 2019-10-05 22:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pictureQ', '0002_auto_20191006_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 5, 22, 33, 56, 864642, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='album',
            name='photos',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='', width_field=500),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 5, 22, 33, 56, 865642, tzinfo=utc)),
        ),
    ]
