# Generated by Django 2.2.1 on 2019-10-05 22:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pictureQ', '0003_auto_20191006_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='height',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='album',
            name='width',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 5, 22, 37, 48, 495891, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='album',
            name='photos',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='', width_field='width'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 5, 22, 37, 48, 496891, tzinfo=utc)),
        ),
    ]
