# Generated by Django 2.2.1 on 2019-10-05 22:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pictureQ', '0004_auto_20191006_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='height',
        ),
        migrations.RemoveField(
            model_name='album',
            name='width',
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 5, 22, 53, 53, 924110, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='album',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 5, 22, 53, 53, 925110, tzinfo=utc)),
        ),
    ]
