# Generated by Django 2.2.1 on 2019-10-07 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pictureQ', '0005_auto_20191006_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 7, 18, 18, 57, 103233, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 7, 18, 18, 57, 103233, tzinfo=utc)),
        ),
    ]
