# Generated by Django 2.2.1 on 2019-10-07 20:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pictureQ', '0008_auto_20191008_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 7, 20, 28, 8, 217873, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 7, 20, 28, 8, 217873, tzinfo=utc)),
        ),
    ]
