# Generated by Django 2.2.1 on 2019-10-08 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pictureQ', '0009_auto_20191008_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 8, 7, 18, 14, 729447, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 8, 7, 18, 14, 729447, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
