# Generated by Django 2.2.1 on 2019-10-08 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureQ', '0010_auto_20191008_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 8, 14, 58, 37, 887420)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 8, 14, 58, 37, 888420), null=True),
        ),
    ]
