# Generated by Django 2.2.1 on 2019-10-08 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureQ', '0011_auto_20191008_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 8, 17, 41, 47, 368186)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 8, 17, 41, 47, 369186), null=True),
        ),
    ]
