# Generated by Django 2.2.1 on 2019-10-19 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureQ', '0014_auto_20191020_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 20, 3, 49, 38, 238695)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 20, 3, 49, 38, 239696), null=True),
        ),
    ]
